# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wyrmsun Development Blog
email: wyrmsun@stratagus.com
description: > # this means to ignore newlines until "baseurl:"
  Wyrmsun is a strategy game that features elements of history, mythology and fiction. Follow this blog to keep up to date with the latest development news!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrettin.github.io/blog" # the base hostname & protocol for your site
twitter_username: wyrmsun
github_username:  Andrettin

# Build settings
markdown: kramdown
